Update Dataframes cleaner.ipynb
Data-dream-team-Laurence/Brief-data-dream-team pull request #16
Opened 2022-12-15 14:59 UTC by MegaMawilite

2022-12-15 15:02 UTC, LaurenceAndraud commented
@ValBaron10 louis a revu les dataframes, peux-tu jeter un coup d’œil ?

2022-12-15 17:15 UTC, ValBaron10 requested changes
Je ne comprends pas pourquoi le fichier est en double (dans et hors du dossier prediction) ?
Ensuite ce fichier est très court (sauf s'il me manque des lignes) et j'y vois juste des corrélations qui sont calculées entre des features. La question que je me pose c'est quelle analyse en est faite ? Qu'avez vous appris de ces résultats ? Là comme ça le fichier est propre et clair, mais que voulez-vous en faire ?

2022-12-16 09:23 UTC, MegaMawilite commented
Je viens de découvrir que le fichier était en double, et je ne sais pas pourquoi ni même comment.
L'analyse devrait arriver aujourd'hui, ce request était surtout pour pouvoir donner les données pour Rémi.

2022-12-16 09:41 UTC, MegaMawilite commented
@ValBaron10 Es-que tu peux vérifier si ce que j'ai fait est ok?

2022-12-16 10:52 UTC, ValBaron10 approved these changes
C'est ok pour moi si c'est juste pour passer les codes à Rémi, mais il faut bien expliquer pourquoi vous choisissez des features plutôt que des autres lors de vos différentes prédictions.

2022-12-16 10:53 UTC, LaurenceAndraud approved these changes

2022-12-16 10:54 UTC, merged